<?php
defined('BASEPATH') OR exit('No direct script access allowed');
?><!DOCTYPE html>

<h1 style='margin-top:2.15pt;margin-right:0cm;margin-bottom:0cm;margin-left:5.0pt;font-size:15px;font-family:"Calibri",sans-serif;'>SYARAT&nbsp;DAN&nbsp;KETENTUAN&nbsp;PENGGUNAAN</h1>
<p style='margin-top:1.95pt;margin-right:6.05pt;margin-bottom:0cm;margin-left:5.0pt;text-align:justify;font-size:15px;font-family:"Calibri",sans-serif;line-height:115%;'>Selamat datang di&nbsp;Campus Profile. Terima kasih telah menggunakan aplikasi ini sebagai salah satu&nbsp;tools&nbsp;pembelajaran&nbsp;dalam&nbsp;menganalisis&nbsp;kelayakan&nbsp;suatu&nbsp;industri.&nbsp;Silakan&nbsp;membaca&nbsp;syarat&nbsp;dan&nbsp;ketentuan&nbsp;penggunaan&nbsp;aplikasi&nbsp;ini dengan&nbsp;seksama.</p>
<p style='margin-top:.35pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;text-align:left;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:17px;">&nbsp;</span></p>
<h1 style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:5.0pt;font-size:15px;font-family:"Calibri",sans-serif;'>KETENTUAN&nbsp;UMUM</h1>
<p style='margin-top:1.95pt;margin-right:5.55pt;margin-bottom:0cm;margin-left:5.0pt;text-align:justify;font-size:15px;font-family:"Calibri",sans-serif;line-height:115%;'>Dengan mengunduh, mengakses dan/atau menggunakan aplikasi&nbsp;Campus Profile&nbsp;ini, berarti Anda&nbsp;telah&nbsp;setuju&nbsp;untuk&nbsp;terikat&nbsp;serta&nbsp;tunduk&nbsp;pada&nbsp;Syarat&nbsp;dan&nbsp;Ketentuan&nbsp;Penggunaan&nbsp;aplikasi&nbsp;ini&nbsp;(selanjutnya disebut sebagai &ldquo;Syarat&rdquo;. Atau &ldquo;Ketentuan Layanan&rdquo;, atau &ldquo;Syarat dan Ketentuan&rdquo;. Jika&nbsp;anda&nbsp;tidak&nbsp;menyetujui&nbsp;Syarat&nbsp;dan&nbsp;Ketentuan&nbsp;ini,&nbsp;maka&nbsp;Anda&nbsp;kami&nbsp;sarankan&nbsp;untuk&nbsp;berhenti&nbsp;mengakses&nbsp;dan/atau&nbsp;menggunakan&nbsp;aplikasi&nbsp;Campus Profile&nbsp;ini.</p>
<p style='margin-top:.1pt;margin-right:5.9pt;margin-bottom:.0001pt;margin-left:5.0pt;text-align:justify;font-size:15px;font-family:"Calibri",sans-serif;line-height:113%;'>Anda dilarang untuk menyalahgunakan aplikasi&nbsp;ini&nbsp;dengan cara apapun&nbsp;dan&nbsp;juga tidak diizinkan&nbsp;untuk menggunakan untuk kepentingan yang tidak diizinkan pihak developer.</p>
<p style='margin-top:.4pt;margin-right:5.7pt;margin-bottom:.0001pt;margin-left:5.0pt;text-align:justify;font-size:15px;font-family:"Calibri",sans-serif;line-height:115%;'>Campus Profile&nbsp;berhak&nbsp;untuk&nbsp;melakukan&nbsp;revisi&nbsp;dan&nbsp;perubahan&nbsp;syarat&nbsp;dan&nbsp;ketentuan&nbsp;tanpa&nbsp;terlebih dahulu mendapatkan persetujuan dari Anda. Perubahan dan pengembangan atas syarat dan&nbsp;ketentuan secara berkala, karena penggunaan lanjutan Anda atas Aplikasi&nbsp;Campus Profile&nbsp;akan&nbsp;mengartikan&nbsp;bahwa&nbsp;anda&nbsp;menerima&nbsp;revisi&nbsp;atau&nbsp;pembaharuan&nbsp;apapun.</p>
<p style='margin-top:1.95pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:5.0pt;text-align:left;font-size:15px;font-family:"Calibri",sans-serif;margin:0cm;'><span style="font-size:17px;">&nbsp;</span></p>
<h1 style='margin-top:.05pt;margin-right:0cm;margin-bottom:0cm;margin-left:5.0pt;font-size:15px;font-family:"Calibri",sans-serif;'>TENTANG&nbsp;Campus Profile</h1>
<p style='margin-top:2.2pt;margin-right:5.55pt;margin-bottom:.0001pt;margin-left:5.0pt;text-align:justify;font-size:15px;font-family:"Calibri",sans-serif;line-height:115%;'>Campus Profile&nbsp;merupakan platform yang berbasis aplikasi mobile yang dioperasikan oleh FABA&nbsp;Konsultan untuk keperluan informasi terupdate dari industri-industri tersebut. &ldquo;Pengguna&rdquo; adalah&nbsp;individu&nbsp;dan/atau&nbsp;setiap&nbsp;orang&nbsp;yang&nbsp;diberikan&nbsp;hak&nbsp;oleh&nbsp;Podororo University&nbsp;untuk&nbsp;mengunduh&nbsp;dan&nbsp;menggunakan&nbsp;semua&nbsp;fitur&nbsp;yang&nbsp;terdapat&nbsp;pada&nbsp;Campus Profile.</p>
<p style='margin-top:.25pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;text-align:left;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:17px;">&nbsp;</span></p>
<h1 style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:5.0pt;font-size:15px;font-family:"Calibri",sans-serif;'>TANGGUNG&nbsp;JAWAB</h1>
<p style='margin-top:1.95pt;margin-right:5.75pt;margin-bottom:0cm;margin-left:5.0pt;text-align:justify;font-size:15px;font-family:"Calibri",sans-serif;line-height:115%;'>Dengan menggunakan aplikasi ini, anda setuju bahwa kami tidak bertanggung jawab kepada anda&nbsp;atau pun kepada pihak lainnya untuk segala kerugian yang disebabkan oleh tindakan yang diambil&nbsp;anda atau pihak lain berdasarkan aplikasi ini. Ketentuan tersebut tetap berlaku meskipun anda tidak&nbsp;lagi&nbsp;menggunakan&nbsp;aplikasi&nbsp;Campus Profile.</p>
<p style='margin-top:.25pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;text-align:left;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:17px;">&nbsp;</span></p>
<h1 style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:5.0pt;font-size:15px;font-family:"Calibri",sans-serif;'>KEANGGOTAN&nbsp;CAMPUS PROFILE</h1>
<p style='margin-top:1.95pt;margin-right:5.8pt;margin-bottom:0cm;margin-left:5.0pt;text-align:justify;font-size:15px;font-family:"Calibri",sans-serif;line-height:115%;'>Untuk dapat menggunakan semua fitur yang terdapat di&nbsp;Campus Profile, anda harus&nbsp;terlebih&nbsp;dahulu&nbsp;melakukan&nbsp;pendaftaran/registrasi&nbsp;di&nbsp;Aplikasi&nbsp;dan&nbsp;mohon&nbsp;dipastikan&nbsp;nama&nbsp;anda&nbsp;sudah&nbsp;disetujui&nbsp;oleh&nbsp;pihak&nbsp;Podomoro University&nbsp;untuk&nbsp;menggunakan&nbsp;aplikasi&nbsp;Campus Profile.</p>
<p style='margin-top:.1pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;text-align:left;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:17px;">&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:5.65pt;margin-bottom:.0001pt;margin-left:5.0pt;text-align:justify;font-size:15px;font-family:"Calibri",sans-serif;line-height:115%;'>Kami&nbsp;akan&nbsp;mengumpulkan&nbsp;dan&nbsp;memproses&nbsp;informasi&nbsp;pribadi&nbsp;anda&nbsp;seperti&nbsp;nama,&nbsp;alamat&nbsp;surat&nbsp;elektronik (email), dan nomot telepon seluler anda ketika mendaftar dan informasi pribadi lainnya.&nbsp;Setelah&nbsp;anda&nbsp;berhasil&nbsp;mendaftarkan&nbsp;diri&nbsp;atau&nbsp;melakukan&nbsp;registrasi,&nbsp;aplikasi&nbsp;akan&nbsp;memberikan&nbsp;kepada anda suatu akun pribadi yang dapat diakses dengan kata sandi yang telah anda pilih. Anda&nbsp;berjanji bahwa semua informasi yang anda berikan kepada kami adalah benar, akurat, terkini, dan&nbsp;lengkap, dan anda setuju&nbsp;untuk&nbsp;mempertahankan dan segera memperbaharui&nbsp;informasi&nbsp;tersebut&nbsp;jika terdapat perubahan. Anda tidak dapat mentransfer atau berbagi akun dengan pihak ketiga dan&nbsp;anda bertanggung jawab untuk menjaga kerahasiaan akun anda untuk mengetahui apakah anda&nbsp;adalah&nbsp;pengguna&nbsp;yang&nbsp;mengakses&nbsp;aplikasi untuk&nbsp;semua&nbsp;fitur&nbsp;Campus Profile.</p>
<p><span style='font-size:15px;line-height:115%;font-family:"Calibri",sans-serif;'><br>&nbsp;</span></p>
<p style='margin-top:2.15pt;margin-right:5.6pt;margin-bottom:.0001pt;margin-left:5.0pt;text-align:justify;font-size:15px;font-family:"Calibri",sans-serif;line-height:115%;'>Jika&nbsp;seseorang&nbsp;mengakses&nbsp;aplikasi&nbsp;Campus Profile&nbsp;menggunakan&nbsp;akun&nbsp;anda,&nbsp;kami&nbsp;akan&nbsp;bergantung pada akun tersebut dan akan menganggap bahwa itu adalah benar-benar anda yang&nbsp;mengakses aplikasi&nbsp;Campus Profile. Anda bertanggung jawab untuk setiap dan semua penggunaan&nbsp;dan&nbsp;semua&nbsp;aktivitas&nbsp;yang&nbsp;terjadi dalam&nbsp;atau&nbsp;sehubungan&nbsp;dengan&nbsp;akun&nbsp;tersebut.</p>
<p style='margin-top:.3pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;text-align:left;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:17px;">&nbsp;</span></p>
<h1 style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:5.0pt;font-size:15px;font-family:"Calibri",sans-serif;'>INFORMASI&nbsp;YANG&nbsp;KAMI&nbsp;KUMPULKAN</h1>
<p style='margin-top:1.95pt;margin-right:5.45pt;margin-bottom:0cm;margin-left:5.0pt;text-align:justify;font-size:15px;font-family:"Calibri",sans-serif;line-height:115%;'>Kami&nbsp;mengumpulkan&nbsp;informasi&nbsp;yang&nbsp;Anda&nbsp;berikan&nbsp;kepada&nbsp;kami&nbsp;secara&nbsp;langsung&nbsp;melalui&nbsp;menu&nbsp;register dengan memasukan nama pengguna, alamat email, telepon, dan kata sandi untuk membuat&nbsp;akun&nbsp;Campus Profile.&nbsp;Saat Anda menggunakan aplikasi&nbsp;Campus Profile, server kami&nbsp;secara&nbsp;otomatis merekam informasi file log, jumlah klik, dan bagaimana anda berinteraksi dengan semua&nbsp;fitur e-&nbsp;Campus Profile. Informasi tersebut dapat membantu pelaporan yang lebih akurat dan untuk&nbsp;penyempurnaan&nbsp;layanan&nbsp;aplikasi&nbsp;Campus Profile</p>
<p style='margin-top:.1pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;text-align:left;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:17px;">&nbsp;</span></p>
<h1 style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:5.0pt;font-size:15px;font-family:"Calibri",sans-serif;'>BAGAIMANA&nbsp;KAMI&nbsp;MELINDUNGI&nbsp;INFORMASI&nbsp;ANDA</h1>
<p style='margin-top:2.2pt;margin-right:5.85pt;margin-bottom:.0001pt;margin-left:5.0pt;text-align:justify;font-size:15px;font-family:"Calibri",sans-serif;line-height:115%;'>Kami&nbsp;menerapkan&nbsp;praktik&nbsp;pengumpulan,&nbsp;penyimpanan,&nbsp;dan&nbsp;pengolahan&nbsp;data&nbsp;yang&nbsp;tepat&nbsp;dan&nbsp;tindakan&nbsp;pengamanan&nbsp;untuk&nbsp;melindungi&nbsp;akses,&nbsp;perubahan,&nbsp;pengungkapan,&nbsp;atau&nbsp;penghancuran&nbsp;informasi pribadi, nama pengguna, kata sandi, dan data yang tersimpan di aplikasi kami secara tidak&nbsp;sah.</p>
<p style='margin-top:1.95pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:5.0pt;text-align:left;font-size:15px;font-family:"Calibri",sans-serif;margin:0cm;'><span style="font-size:17px;">&nbsp;</span></p>
<h1 style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:5.0pt;font-size:15px;font-family:"Calibri",sans-serif;'>BERBAGI&nbsp;INFORMASI&nbsp;PRIBADI&nbsp;ANDA</h1>
<p style='margin-top:2.2pt;margin-right:5.6pt;margin-bottom:.0001pt;margin-left:5.0pt;text-align:justify;font-size:15px;font-family:"Calibri",sans-serif;line-height:115%;'>Kami sangat menghargai privasi Anda, kami tidak menjual, memperdagangkan, atau menyewakan&nbsp;informasi identifikasi pribadi pengguna kepada orang lain tanpa persetujuan dari Anda. Kami dapat&nbsp;membagikan informasi demografis gabungan generik yang tidak terkait dengan informasi pribadi&nbsp;apapun&nbsp;untuk&nbsp;sebagai&nbsp;laporan&nbsp;kami kepada&nbsp;pihak&nbsp;pemberi kerja&nbsp;(user).</p>
<p style='margin-top:.25pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;text-align:left;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:17px;">&nbsp;</span></p>
<h1 style='margin-top:.05pt;margin-right:0cm;margin-bottom:0cm;margin-left:5.0pt;font-size:15px;font-family:"Calibri",sans-serif;'>KONTEN&nbsp;APLIKASI</h1>
<p style='margin-top:1.9pt;margin-right:5.55pt;margin-bottom:.0001pt;margin-left:5.0pt;text-align:justify;font-size:15px;font-family:"Calibri",sans-serif;line-height:115%;'>Seluruh konten aplikasi&nbsp;Campus Profile&nbsp;merupakan kerjasama dengan berbagai pihak di&nbsp;Podomoro Unviersity.&nbsp;Kami&nbsp;bertanggung&nbsp;jawab&nbsp;dalam&nbsp;mengupdate&nbsp;setiap&nbsp;informasi&nbsp;yang&nbsp;berkaitan&nbsp;dengan&nbsp;industri&nbsp;yang&nbsp;telah&nbsp;dipilih&nbsp;oleh&nbsp;Podomoro University.</p>
<p style='margin-top:.15pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;text-align:left;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:17px;">&nbsp;</span></p>
<h1 style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:5.0pt;font-size:15px;font-family:"Calibri",sans-serif;'>KONEKSI&nbsp;ANDA&nbsp;KE&nbsp;APLIKASI&nbsp;LAIN</h1>
<p style='margin-top:2.15pt;margin-right:5.55pt;margin-bottom:.0001pt;margin-left:5.0pt;text-align:justify;font-size:15px;font-family:"Calibri",sans-serif;line-height:115%;'>Untuk&nbsp;keperluan&nbsp;referensi&nbsp;anda,&nbsp;pada&nbsp;aplikasi&nbsp;terdapat&nbsp;tautan&nbsp;ke&nbsp;aplikasi-aplikasi&nbsp;lain&nbsp;yang&nbsp;dicantumkan&nbsp;oleh&nbsp;kami.&nbsp;Namun,&nbsp;ketika&nbsp;anda&nbsp;menggunakan&nbsp;tautan-tautan&nbsp;tersebut,&nbsp;kami&nbsp;tidak&nbsp;bertanggung&nbsp;jawab&nbsp;untuk&nbsp;melindungi&nbsp;privasi&nbsp;dan&nbsp;informasi&nbsp;apapun&nbsp;yang&nbsp;anda&nbsp;berikan&nbsp;ketika&nbsp;mengunjungi aplikasi-aplikasi tersebut. Kami juga tidak bertanggung atas konten yang ditimbulkan&nbsp;akibat mengakses aplikasi-aplikasi tersebut. Anda harus mempelajari dan membaca dengan hati-hati&nbsp;kebijakan&nbsp;penanganan&nbsp;informasi pribadi yang&nbsp;berlaku&nbsp;di&nbsp;aplikasi tersebut.</p>
<p style='margin-top:.1pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;text-align:left;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:17px;">&nbsp;</span></p>
<h1 style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:5.0pt;font-size:15px;font-family:"Calibri",sans-serif;'>PERUBAHAN&nbsp;TERHADAP&nbsp;KEBIJAKAN&nbsp;PRIVASI&nbsp;KAMI</h1>
<p style='margin-top:1.95pt;margin-right:5.75pt;margin-bottom:0cm;margin-left:5.0pt;text-align:justify;font-size:15px;font-family:"Calibri",sans-serif;line-height:115%;'>Campus Profile&nbsp;dapat memodifikasi atau memperbarui Kebijakan Privasi ini dari waktu ke waktu,&nbsp;jadi&nbsp;mohon&nbsp;tinjau&nbsp;secara&nbsp;berkala.&nbsp;Kami&nbsp;dapat&nbsp;menyediakan&nbsp;bentuk&nbsp;pemberitahuan&nbsp;tambahan&nbsp;tentang perubahan atau pembaruan jika sesuai dengan keadaan. Kami menganggap Anda menerima&nbsp;perubahan&nbsp;tersebut&nbsp;apabila&nbsp;Anda&nbsp;terus&nbsp;menggunakan&nbsp;Campus Profile&nbsp;setelah&nbsp;mengetahui&nbsp;perubahan&nbsp;terhadap&nbsp;Kebijakan&nbsp;Privasi&nbsp;ini.</p>
<p><span style='font-size:15px;line-height:115%;font-family:"Calibri",sans-serif;'><br>&nbsp;</span></p>
<h1 style='margin-top:2.15pt;margin-right:0cm;margin-bottom:0cm;margin-left:5.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>PENERIMAAN&nbsp;ANDA&nbsp;TERHADAP&nbsp;PERSYARATAN&nbsp;INI</h1>
<p style='margin-top:1.95pt;margin-right:5.8pt;margin-bottom:0cm;margin-left:5.0pt;text-align:justify;font-size:15px;font-family:"Calibri",sans-serif;line-height:115%;'>Dengan menggunakan aplikasi&nbsp;Campus Profile, Anda menandakan penerimaan Anda terhadap&nbsp;kebijakan&nbsp;ini.&nbsp;Jika&nbsp;Anda&nbsp;tidak&nbsp;menyetuju&nbsp;kebijakan&nbsp;ini,&nbsp;mohon&nbsp;jangan&nbsp;gunakan&nbsp;aplikasi dari kami.</p>
<p style='margin-top:.55pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;text-align:left;font-size:15px;font-family:"Calibri",sans-serif;'><span style="font-size:16px;">&nbsp;</span></p>
<h1 style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:5.0pt;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'>CARA&nbsp;MENGHUBUNGI&nbsp;KAMI</h1>
<p style='margin-top:2.2pt;margin-right:5.4pt;margin-bottom:.0001pt;margin-left:5.0pt;text-align:justify;font-size:15px;font-family:"Calibri",sans-serif;line-height:113%;'>Jika anda memiliki pertanyaan tentang Kebjakan Privasi atau fitur layanan aplikasi&nbsp;Campus Profile,&nbsp;silakan temukan saluran dukungan yang sesuai di Pusat Bantuan untuk menghubungi&nbsp;kami atau&nbsp;dapat&nbsp;melalui email&nbsp;<a href="mailto:it@podomorouniversity.ac.id">it@podomorouniversity.ac.id</a></p>

</html>